subcomponents:
  project-jackson:
    subcomponents:
      services:
        subcomponents:
          project-jackson:
            subcomponents:
              jackson-api:
                subcomponents:
                  stable:
                    config:
                      image:
                        repository: mtarng/jackson-api
                        tag: v1.1-peoplehobby
              jackson-ui:
                subcomponents:
                  stable:
                    config:
                      image:
                        repository: mtarng/jackson-ui
                        tag: v1.0
